### ISSUE TITLE
Build Process

### ISSUE THREAD

**Issue by mrschick** [pastoman/Arma-3-Portable-Drone-mod#1]
First of all, thanks for putting this on GitHub, I'm sure it will lead to some nice contributions 👍🏻

To start out, maybe the build process could be made more user-friendly.
Now, I don't have much experience with building mods, so I might be missing something or doing it wrong, but to package the files in this repo into a valid mod directory tree and PBOs, I had to first extract the `meta/mod.cpp` files from the public version and move a bunch of folders around before getting the Arma 3 Tools Addon Builder to run.

Could we add all files required to build the mod to this repo, as well as make a section of the README explain how to do so?

Additionally, we could also set up [HEMTT](https://github.com/BrettMayson/HEMTT) to greatly improve the development process thanks to its [dev builds](https://brettmayson.github.io/HEMTT/commands/dev.html), which allows you to work on SQF without having to recompile and relaunch Arma 3 every time to test a new change, instead you only need to restart the test mission.

**Comment by pastoman** [comment]
That would be handy, there is pretty much everything that is needed for building arma 3 addon except for the fact that it  is missing mod.cpp and that the file structure is different from the one that I use. I will reorganize it and write more detailed instructions for building addon. When it comes to HEMTT, I do not have any experiences with it, but I might look at it when I will have slightly more time. I won't be able to get to it sooner then on this weekend.

**Comment by mrschick** [comment]
Just found the following guide, might be useful.
https://github.com/acemod/arma-project-template
