### ISSUE TITLE
Q: Where are the tagged releases

### ISSUE THREAD

**Issue by mwpowellhtx** [pastoman/Arma-3-Portable-Drone-mod#6]
Did not see any tagged releases there, what all changed, exactly? Thanks... Cheers 🍻

**Comment by mwpowellhtx** [comment]
Follow on question, what was the bikey name previous to the latest version? At the moment I have, `DRNP_1.1.0.1.bikey`. Just do not want to let bad or old keys remain on my servers. Thank you...

**Comment by pastoman** [comment]
Hello, I will release tagged version of the mod on github in two days, I'm currently not at home. When it comes to that key, the old name was:  _SKFG.bikey_

**Comment by pastoman** [comment]
But the only changes were the camo fix and restructuralisation of mod's file structure. I will try to look at that client side spawning issue this week.

**Comment by mwpowellhtx** [comment]
No worries, no rush on anything. Just keeping up to date, and the file system squared. Cheers mate. 🍻
